[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
helloinit = "DmbWbQj8c21AzuBkL4DsiyK12bnyVvPGqs2EsLzbjhYi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/salmanhayat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
